### ISSUE TITLE
Python scripts doesn't work with ChaquoPy 7.0.2

### ISSUE THREAD

**Issue by VicentIborra** [chaquo/chaquopy#239]
We had an Android project working with Python scripts and ChaquoPy 6.3.0.
I have upgraded ChaquoPy version to 7.0.2 and every python script stops to work. I receive error messages from Python like: ' AttributeError: 'NuSVC' object has no attribute 'break_ties'. 

It seems a problem with some libraries (this libraries work ok with 6.3 version).

Is Chaquopy installing another version of this libraries? 
If I try to install one version with 'install "scikit-learn==2.21.2" in build.gradle(:app), I receive an error: Process 'command 'py'' finished with non-zero exit value 1.
How can I run the same scripts with ChaquoPy 7.0.2? I'm running Python 3.7.6 with option buildPython "py -3.7".

**Comment by mhsmith** [comment]
>  I receive error messages from Python like: ' AttributeError: 'NuSVC' object has no attribute 'break_ties'.

Please provide the full error message and stack trace.

> If I try to install one version with 'install "scikit-learn==2.21.2" in build.gradle(:app), I receive an error: Process 'command 'py'' finished with non-zero exit value 1.

Chaquopy 6.3.0 include scikit-learn 0.21.2, but with Chaquopy 7.0.2 you'll have to upgrade to version 0.22.1.

**Comment by mhsmith** [comment]
> I receive error messages from Python like: ' AttributeError: 'NuSVC' object has no attribute 'break_ties'.

From the [scikit-learn release notes](https://scikit-learn.org/stable/whats_new/v0.22.html#sklearn-svm), it looks like the `break_ties` option was added in version 0.22, so that version should work for you.

If this is still a problem, please reopen and provide the full error message and stack trace, along with the source code line which triggers it.
