### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items' in Keras model_from_json

### ISSUE THREAD

**Issue by VicentIborra** [chaquo/chaquopy#325]
We have an app working with Chaquopy 6.3.0. We have to migrate to Chaquopy 8.0.0 in order to use Python in an ARR.
I have some problems to load models with TensorFlow 2.1.0:
https://github.com/tensorflow/tensorflow/issues/35942

This issue doesn't appears in versions 2.0.0 or 1.10.1 of TensorFlow, but I only can install 2.1.0 version with Chaquopy 8.0.0
If I try to install any version, I receive the same error:
Could not find a version that satisfies the requirement tensorflow==2.0.0 (from versions: 2.1.0)
Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.1.0)

How can I install TensorFlow 2.0.0 using Chaquopy 8.0.0?

Thanks!

**Comment by mhsmith** [comment]
What exactly was the error you received?

If we provide any other version of TensorFlow, it would probably be the current one, 2.2.0. Can you confirm that version would fix your problem?

**Comment by VicentIborra** [comment]
This is the error returned by Python:
AttributeError: 'list' object has no attribute 'items'

Related to these lines:
from tensorflow.keras.models import model_from_json
model = model_from_json(loaded_model_json)

I know that this error is fixed with 2.0.0 version. I can't confirm in 2.2.0 version, but probably it's fixed too:
https://github.com/tensorflow/tensorflow/issues/35942#issuecomment-640929203

**Comment by mhsmith** [comment]
That error message doesn't appear anywhere in the linked TensorFlow issue. Why do you think it's related?

Post the full stack trace please.

**Comment by VicentIborra** [comment]
Traceback (most recent call last):
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/app/CVscript_All_images.py", line 36, in baseline_model_saved
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:     model_from_json(loaded_model_json)
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/tensorflow_core/python/keras/saving/model_config.py", line 96, in model_from_json
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:     return deserialize(config, custom_objects=custom_objects)
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
2020-06-30 13:18:10.576 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:     return deserialize_keras_object(
2020-06-30 13:18:10.577 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/tensorflow_core/python/keras/utils/generic_utils.py", line 291, in deserialize_keras_object
2020-06-30 13:18:10.577 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:     (cls, cls_config) = class_and_config_for_serialized_keras_object(
2020-06-30 13:18:10.577 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/tensorflow_core/python/keras/utils/generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
2020-06-30 13:18:10.577 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr:     for key, item in cls_config.items():
2020-06-30 13:18:10.577 12889-23674/eu.h2020.helios_social.heliostestclient W/python.stderr: AttributeError: 'list' object has no attribute 'items'

**Comment by VicentIborra** [comment]
Keras Model Errors on Loading - 'list' object has no attribute 'items':
https://github.com/tensorflow/tensorflow/issues/35934

Here you can see this issue with TensorFlow version 2.1.0

We have tested same script in two Python environments. Using TensorFlow 2.0.0, the script runs fine.

When do you think another version of TensorFlow will be available? Thanks.

**Comment by mhsmith** [comment]
OK, that link seems more relevant, thanks. It looks like it's caused by generating a model with TensorFlow 1.x and loading it with TensorFlow 2.1. And they say it will be fixed in TensorFlow 2.3.

Unfortunately we can't provide TensorFlow 2.0.0 because it's not compatible with Python 3.8. So I think your options are:

* Wait for the release of TensorFlow 2.3; or
* Regenerate your model with TensorFlow 2.x.

**Comment by VicentIborra** [comment]
Thanks Malcolm! Yes, probably we can fix issue re-generating the model with 2.1.0. I go to try it.

**Comment by VicentIborra** [comment]
Hi Malcolm,
It's not possible re-generate model with version 2.1 of TensorFlow (we haven't the source of that model).
I tried to load _model_from_json_ from Keras library instead of TensorFlow. I receive other error:

com.chaquo.python.PyException: ImportError: Keras requires TensorFlow 2.2 or higher.

I understand it's not possible to install TensorFlow 1.10.1 to upload our model. Do you think it's possible to include TensorFlow 2.2 version in Chaquopy 8.0, please?

Thanks!

**Comment by mhsmith** [comment]
As it says in the [Keras release notes](https://github.com/keras-team/keras/releases), the current version of the standalone Keras package (2.4.0) simply redirects to `tensorflow.keras`. Since the bug you're facing hasn't been fixed in TensorFlow 2.2, this approach wouldn't solve your problem.

Instead, you could try using the previous version, Keras 2.3.1. This claims to be compatible with TensorFlow 2.0, so perhaps it's compatible with TensorFlow 2.1 as well.

**Comment by mhsmith** [comment]
Perhaps you could also use TensorFlow 2.0 to bridge the compatibility gap. That is:

* Use TensorFlow 2.0 to load your 1.x model
* Save your model to a new file
* Try loading the new file on TensorFlow 2.1

I'm not very familiar with this area so I don't know if that will work, but it's worth a try.

**Comment by VicentIborra** [comment]
With Keras 2.3.1, I get this error:

Traceback (most recent call last):
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/app/CVscript_All_images.py", line 37, in baseline_model_saved
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     model_from_json(loaded_model_json)
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/engine/saving.py", line 664, in model_from_json
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     return deserialize(config, custom_objects=custom_objects)
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/layers/__init__.py", line 165, in deserialize
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     return deserialize_keras_object(config,
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
2020-07-06 09:04:36.427 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     return cls.from_config(
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/engine/sequential.py", line 302, in from_config
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     model.add(layer)
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/engine/sequential.py", line 159, in add
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     x = Input(
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/engine/input_layer.py", line 175, in Input
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     input_layer = InputLayer(batch_input_shape=batch_shape,
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/legacy/interfaces.py", line 91, in wrapper
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     return func(*args, **kwargs)
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/engine/input_layer.py", line 84, in __init__
2020-07-06 09:04:36.428 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     input_tensor = K.placeholder(shape=batch_input_shape,
2020-07-06 09:04:36.429 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:   File "/data/user/0/eu.h2020.helios_social.heliostestclient/files/chaquopy/AssetFinder/requirements/keras/backend/tensorflow_backend.py", line 73, in symbolic_fn_wrapper
2020-07-06 09:04:36.429 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr:     if _SYMBOLIC_SCOPE.value:
2020-07-06 09:04:36.429 14413-18240/eu.h2020.helios_social.heliostestclient W/python.stderr: AttributeError: '_thread._local' object has no attribute 'value'

**Comment by mhsmith** [comment]
Like I said, I don't know whether Keras 2.3.x is compatible with TensorFlow 2.1.x. Does the same problem occur with the same combination of versions on another platform? If so, this error probably has nothing to do with Chaquopy, and you should search for it elsewhere.

**Comment by VicentIborra** [comment]
Hi Malcolm,
We have fixed this issue with a mix of your suggerstions:

- From a Python script, open the model for TF 1.10 with Tensorflow 2.0

- Save model into a new file

- In app Python script, we load the new model:
json_file = open(dirpath + '/new_model.json', 'r')

- build.gradle (Module: app) config:

python {
            **//using Python 3.7.7**
            buildPython "C:/Users/user_name/AppData/Local/Programs/Python/Python37/python.exe"
            pip {
                install "numpy"
                install "scipy"
                install "scikit-learn"
                install "argparse"
                install "opencv-python"
                install "matplotlib"
                **install "keras==2.3.1"**
                install "tensorflow"
                install "textblob"
                install "nltk"
                install "request"
                install "--no-binary=h5py h5py"
            }
        }

Thanks very much!
