### ISSUE TITLE
Not able to install imutils, cv2, time, os, math in Chaquo 

### ISSUE THREAD

**Issue by jyoti1404** [chaquo/chaquopy#510]
#### Chaquopy version

I use Python 3.8 with Chaquopy 7.0

#### Relevant parts of your code

python {
            pip {
                install "numpy"
                install "argparse"
                install "opencv-python"
                install "imutils"
                install "math"
                install "cv2"
                install "time"
                install "os"
            }

#### Describe your issue

Collecting imutils
  Using cached https://files.pythonhosted.org/packages/3f/d3/ecb4d108f6c1041d24842a345ee0123cd7f366ba75cf122601e856d42ba2/imutils-0.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\Hp\AndroidStudioProjects\Corona\app\build\generated\python\bp.zip\setuptools\__init__.py", line 14, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\Hp\AndroidStudioProjects\Corona\app\build\generated\python\bp.zip\setuptools\dist.py", line 24, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\Hp\AndroidStudioProjects\Corona\app\build\generated\python\bp.zip\setuptools\depends.py", line 7, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\Hp\AndroidStudioProjects\Corona\app\build\generated\python\bp.zip\setuptools\py33compat.py", line 54, in <module>
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Hp\AppData\Local\Temp\pip-install-makw5clt\imutils\
ERROR: Failed to install imutils from https://files.pythonhosted.org/packages/3f/d3/ecb4d108f6c1041d24842a345ee0123cd7f366ba75cf122601e856d42ba2/imutils-0.5.4.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
> AttributeError: 'HTMLParser' object has no attribute 'unescape'

See #416. This can be fixed by upgrading to Chaquopy 9.1.0 or newer, or using the `buildPython` setting to build with Python 3.8 or older.

> install "argparse"
> install "math"
> install "time"
> install "os"

These are standard library modules which are always available, so you should remove these lines.

> install "cv2"

The pip package name is "opencv-python", which you've already listed, so you should remove this line as well.
