### ISSUE TITLE
Hello World?

### ISSUE THREAD

**Issue by Enteleform** [chaquo/chaquopy#16]
Any chance you could split the `Android activity written entirely in Python` into a separate repo?&nbsp; It could even be simplified to the 'Hello World' level, with just a TextView & Button.

The demo is great, but it's been tricky to figure out the bare minimum that's necessary to make it work in isolation.

**Comment by mhsmith** [comment]
I'd rather not make a separate repo, as it would multiply the work of creating each new release. But I agree there are some things which might make it hard to see how to make the UI demo activity work in isolation:

* In `src/main/python`, the UI demo activity has its own package, but all other Python code is intermixed at the top-level, making it unclear what's relevant to what.
* The layout file file is called `activity_menu`: for consistency it should be called `activity_ui_demo`.
* The Python configuration lines in build.gradle don't indicate what part of the app each one is for.

Are there any other things you found unclear?

**Comment by Enteleform** [comment]
I'm trying to recreate the standard Android Studio `Empty Activity` template, so I created
`python.com.example.my_app.main_activity`
instead of 
`java.com.example.my_app.java.MainActivity`

-----

I've resolved a few issues by examining the documentation & `ui_demo.py`.

One of the issues was that there's a typo in the documentation @ [**Android > Development**](https://chaquo.com/chaquopy/doc/current/android.html#development).

`android:name="com.chaquo.python.PyApplication"`
should be
`android:name="com.chaquo.python.android.PyApplication"`

-----

At this point, I'm trying to figure out how to access `R` from the python activity.&nbsp; Your example uses `from com.chaquo.python.demo import R`, but I'm not sure how to access it from a root-level activity.

This is the code I'm using:

```python
from java import *

# from com.example.my_app import R
#   throws com.chaquo.python.PyException: ImportError: cannot import name R

from android.os             import Bundle
from android.support.v7.app import AppCompatActivity


class MainActivity(static_proxy(AppCompatActivity)):
  
  @Override(jvoid, [Bundle])
  def onCreate(self, state):
    AppCompatActivity.onCreate(self, state)
    self.setContentView(R.layout.activity_main)

    label = self.findViewById(R.id.label)
    label.setText("Hello World")
```

**Comment by Enteleform** [comment]
> I'd rather not make a separate repo, as it would multiply the work of creating each new release.

Another alternative would be to provide complete, self-contained "Hello World" style snippets in a `Getting Started` section of the documentation. (*see [**Kivy**](https://kivy.org/docs/guide/basic.html) for a good example*).

This is a great project, but IMO it needs some simplified examples so that it's more accessible.&nbsp; Is there a public repo for the documentation?

**Comment by mhsmith** [comment]
> `android:name="com.chaquo.python.PyApplication"` should be `android:name="com.chaquo.python.android.PyApplication"`

Thanks, corrected. There's no public repo for the documentation at the moment; please report any other issues in this repo.

Having thought a bit more about your suggestion, I think you're right that it would be good to have a more minimal example project for Python programmers. If you want to put your template project up once you get it working, I'd be happy to fork it and make it official.

**Comment by mhsmith** [comment]
> Your example uses from com.chaquo.python.demo import R, but I'm not sure how to access it from a root-level activity.

If by "root-level activity" you mean one launched directly from the apps menu, that shouldn't make any difference here. Since your error message says `cannot import name R` rather than `no module named com.example.my_app`, I think it's found a Python package with that name, but not a Java package. (If it found both, the import hook should have given a different error of its own.) 

So are you sure that `com.example.my_app` is actually the package ID of your app? The `R` class will be generated in the package specified in the `<manifest>` element in `AndroidManifest.xml`. If you've set that to `python.com.example.my_app`, then that's the package you should import from.

**Comment by mhsmith** [comment]
>  If you want to put your template project up once you get it working

Or if you want to put it up before you get it working, I can probably help you get it working faster.

**Comment by Enteleform** [comment]
Ok, got it working with the following:

-----

**app/src/main/python/com/example/my_app/main_activity.py:**
changed 
`from com.example.my_app import R`
to 
`from com.example.my_app.main_activity import R`

-----

**app/src/main/res/layout/activity_main.xml:**
changed
`tools:context = com.example.my_app.MainActivity`
to
`tools:context = "com.example.my_app.main_activity.MainActivity"`

-----

**app/src/main/AndroidManifest.xml:**
changed
`manifest package = "com.example.my_app"`
to 
`manifest package = "com.example.my_app.main_activity"`

**Comment by Enteleform** [comment]
> If you want to put your template project up once you get it working, I'd be happy to fork it and make it official.

Cool, I'll clean them up a bit & post them soon. Got two so far - one for using python objects in Java/Kotlin, & the one mentioned in this thread for 100% Python.

Also, by 'cleaning them up' I mean that I had implemented a wrapper over PyObject, so I'll have to strip it back down to a basic implementation. Here's what it does (*in Kotlin, at least*) in case you're interested:
```kotlin
val my_module = PyModule("my_module")
// All [] & () usages return PyObject wrapper,
//   via operator overloading of 'get' and 'invoke'.

//##  Basic Type-Casting  ##//
val a = my_module["some_var"].obj     //  ->  com.chaquo.python.PyObject
val b = my_module["some_var"].str     //  ->  String
val c = my_module["some_var"].int     //  ->  Int
val d = my_module["some_var"].float   //  ->  Float
val e = my_module["some_var"].double  //  ->  Double
val f = my_module["some_var"].long    //  ->  Long
val g = my_module["some_var"].bool    //  ->  Boolean
val h = my_module["some_var"].list    //  ->  MutableList
val i = my_module["some_var"].dict    //  ->  MutableMap

//##  Chainable Parameters & Functions  ##//
val j = my_module["some_object"]["some_parameter"]["sub_parameter"].str
val k = my_module["some_object"]("some_method", 1, 2).int
```

**Comment by mhsmith** [comment]
> Seems like everything just needs to be defined one level further than usual, compared to a pure Java implementation.

That's true in the case of the Python activity class, since you need to specify both the module name and the class name. (In Java, you might say a "module" and a top-level class are one and the same, so the issue doesn't arise.)

But there's no need to change the app ID as well. If you revert the above changes in the `import` statement and the `<manifest>` package, it should still work. 

My guess is that maybe you changed the `<manifest>` package because you'd written something like `<activity android:name=".MainActivity">`, and it wasn't finding it. A better solution to that would be to include the module name in the activity declaration, but still using relative syntax, as the demo app does [here](https://github.com/chaquo/chaquopy/blob/82eefa26ae4838f15c6c8afebb45e5e1f88429ce/app/src/main/AndroidManifest.xml#L28). That way, you have the option to add multiple modules as you develop your app.

**Comment by Enteleform** [comment]
Cool, fixed those relative syntax issues you mentioned. Thanks for the help 👍 

I ended up writing a `Getting Started` documentation section, figured it would be better to cover the exact changes that need to be made in order to get Chaquopy up & running.

Check it out @
- [**ReadTheDocs**](http://chaquopy-getting-started.readthedocs.io)
- [**GitHub**](https://github.com/enteleform-docs/chaquopy_getting_started)

### Notes:
The commits are a mess, no useful info at all lol. It was my first time working with `ReadTheDocs` & `rst`, so I was mostly just figuring out how they work & playing around with formatting. It's not 100% where I'd like it to be, but still pretty passable. Gonna have to learn how to work with templates, apply css, & make custom directives.

**Comment by Enteleform** [comment]
Also, is there any reason that you mirror Java's package directory hierarchy in your demo?

IE:
`python.com.example.my_app`
vs
`python.my_app`

I tried it the second way and it seems to work fine after updating the necessary configuration references.

**Comment by mhsmith** [comment]
> I ended up writing a Getting Started documentation section

That's great: do I have your permission to include parts of it in the official docs?

> is there any reason that you mirror Java's package directory hierarchy in your demo?

I think I just wanted to demonstrate the package-relative syntax in the manifest. Using a top-level module is also fine: in fact it may be better, since it avoids confusion between the Python and Java namespaces.

**Comment by Enteleform** [comment]
> That's great: do I have your permission to include parts of it in the official docs?

Definitely 👍

**Comment by mhsmith** [comment]
I've created a new repo based on your idea: [chaquo/chaquopy-hello](https://github.com/chaquo/chaquopy-hello). Thanks for the suggestion.

**Comment by mhsmith** [comment]
Hi @Enteleform. Thanks again for writing that getting started guide. However, it's now a couple of years out of date, and it looks like some people are still finding it and using a very old version of Chaquopy as a result (e.g. #164). 

So I'd like to request that you take the guide down. I'm sure it was helpful for a lot of people, but now that the [chaquopy-hello](https://github.com/chaquo/chaquopy-hello) template exists, I think it's better for users to start from that, rather than having to go through the whole step-by-step process of creating a new project.

Thanks for understanding.

**Comment by Enteleform** [comment]
Ok, I just deleted the guide from my ReadTheDocs account.

**Comment by mhsmith** [comment]
Thanks.

**Comment by advent-embedded** [comment]
My app permission doesn't work despite adding to manifest file, i even tried adding to run-time permission to oncreate method of mainactivity but none works.
