### PR TITLE
Add package: miniaudio

### PR DESCRIPTION
**Pull request by IsakTheHacker**
Build works on all Android ABIs for Python 3.8!

### CODE REVIEW

**Comment by mhsmith** [comment]
Thanks very much. Could you add some tests of the package's basic functionality? For example, you could write a test that loads a small MP3 file and checks that it has the correct duration, sample format and number of channels. See packages/pillow/test for an example, and see [the bottom of the README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md#testing-a-package) for how to run the test.

**Comment by IsakTheHacker** [comment]
I've added the tests you described but they are failing with a not so descriptive error message:
```
test_mp3_info (chaquopy.test.miniaudio.TestMiniaudio) ... 
ERROR

======================================================================
ERROR: test_mp3_info (chaquopy.test.miniaudio.TestMiniaudio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/data/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/app/chaquopy/test/miniaudio/__init__.py", line 7, in test_mp3_info
    import miniaudio
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/data/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/miniaudio.py", line 22, in <module>
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "import.pxi", line 20, in java.chaquopy.import_override
ModuleNotFoundError: No module named '_miniaudio'

----------------------------------------------------------------------
Ran 1 test in 0.029s

FAILED (errors=1)
```

**Comment by mhsmith** [comment]
I built a wheel file with the current version of this PR and examined it with an unzip tool, and it didn't contain a `_miniaudio` module:
```
Archive:  dist/miniaudio/miniaudio-1.59-0-cp38-cp38-android_21_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    82005  2023-06-04 14:39   miniaudio.py
     1166  2023-07-05 08:22   miniaudio-1.59.dist-info/LICENSE
    25051  2023-07-05 08:22   miniaudio-1.59.dist-info/METADATA
      110  2023-07-05 08:22   miniaudio-1.59.dist-info/WHEEL
       10  2023-07-05 08:22   miniaudio-1.59.dist-info/top_level.txt
      463  2023-07-05 08:22   miniaudio-1.59.dist-info/RECORD
---------                     -------
   108805                     6 files
```

This is because `cffi` is missing from the meta.yaml file. You had it in [your previous version](https://github.com/IsakTheHacker/chaquopy-build-wheel/blob/0a5c6119a08491a7381e39b3c781e54a58f27156/server/pypi/packages/miniaudio/meta.yaml), so I'm not sure why you removed it.

If I add it back and rebuild, the wheel file now contains a `_miniaudio` module:
```
Archive:  dist/miniaudio/miniaudio-1.59-0-cp38-cp38-android_21_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
   855368  2023-07-05 08:27   _miniaudio.so
    82005  2023-06-04 14:39   miniaudio.py
     1166  2023-07-05 08:27   miniaudio-1.59.dist-info/LICENSE
    25051  2023-07-05 08:27   miniaudio-1.59.dist-info/METADATA
      111  2023-07-05 08:27   miniaudio-1.59.dist-info/WHEEL
       21  2023-07-05 08:27   miniaudio-1.59.dist-info/top_level.txt
      535  2023-07-05 08:27   miniaudio-1.59.dist-info/RECORD
---------                     -------
   964257                     7 files
```

Please try that, and let me know if it passes the tests.

**Comment by mhsmith** [comment]
Was that change enough to pass the tests?

**Comment by IsakTheHacker** [comment]
I hope so, I wasn't able to test it because it failed to build the package. I tested and it doesn't have anything to do with the changes to meta.yaml. All package builds have started to fail on my machine recently, with this error:
```
AttributeError: module 'distutils' has no attribute 'filelist'
```
Including miniaudio, bcrypt, bitarray and aiohttp. All the same!

Most likely some update that broke my Python configuration (Fedora Linux btw) but the errors are always so missleading so I don't really know what to do now. Python 3.11 package builds fail with an entirely different error:
```
crtbegin_so.o is incompatible with elf64-x86-64
libpython3.11.so is incompatible with elf64-x86-64
crtend_so.o is incompatible with elf64-x86-64
```

It would be amazing, and I would love to assist, in creating a new Docker image so I don't have to deal with all of this shit. In the meantime, maybe you can run the tests on your setup so we can finally close this PR

**Comment by mhsmith** [comment]
The "is incompatible with elf64-x86-64" error is probably caused by #909, which I'm looking into just now.

But the AttributeError is new to me. If you can still reproduce it, please post a full build log.

**Comment by mhsmith** [comment]
This package is now in the public repository for Python 3.8, 3.9 and 3.10. Thanks for the contribution!

**Comment by mhsmith** [comment]
And if you can send me a full log for the AttributeError, that would still be useful.
